# Generated by Django 5.2.7 on 2025-10-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='bird_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_captured_at', models.DateTimeField(auto_now_add=True)),
                ('times_captured', models.PositiveIntegerField(default=1)),
                ('unlocked', models.BooleanField(default=False)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.bird')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bird')},
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('confidence', models.FloatField()),
                ('ai_fact', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user_bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='birds.userbird')),
            ],
        ),
    ]
