name: CI - Django & FastAPI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # ---------- Django Tests ----------
      - name: Install Django dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        working-directory: backend
        run: |
          python manage.py test

      # ---------- FastAPI Tests ----------
      - name: Install FastAPI dependencies
        working-directory: ml_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run FastAPI tests
        working-directory: ml_service
        run: |
          pytest
